spring:
  application.name: kafka-streams-iq-basic-sample
  cloud:
    stream:
      kafka.streams.binder:
        configuration:
          commit.interval.ms: 1000
      bindings:
        process-in-0:
          destination: products
        process-out-0:
          destination: product-counts
